version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    links:
      - mysql_db:app_db
  mysql_db:
    image: mariadb:10.7.1
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: user-service
      MYSQL_USER: sql
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root